#!/bin/sh
#
# Gradle start up script for POSIX generated by "Gradle init".
#

##############################################################################
# Helper Functions
##############################################################################
warn() { echo "$*"; } >&2
die() { echo; echo "$*"; echo; exit 1; } >&2

##############################################################################
# Main
##############################################################################
APP_HOME=$(cd "$(dirname "$0")" && pwd)
APP_NAME="Gradle"
APP_BASE_NAME="${0##*/}"
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

MAX_FD=maximum
case "$(uname)" in
  CYGWIN* ) cygwin=true  ;;
  Darwin*  ) darwin=true  ;;
  MSYS*|MINGW* ) msys=true ;;
  NONSTOP* ) nonstop=true ;;
esac

if [ -n "$JAVA_HOME" ]; then
  JAVACMD="$JAVA_HOME/bin/java"
  [ -x "$JAVACMD" ] || die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
else
  JAVACMD=java
  which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and 'java' was not found in PATH."
fi

if ! "$cygwin" && ! "$darwin" && ! "$nonstop"; then
  case $MAX_FD in
    max*) MAX_FD=$(ulimit -H -n 2>/dev/null) ;;
  esac
  case $MAX_FD in
    ''|soft) : ;;
    *) ulimit -n "$MAX_FD" 2>/dev/null || warn "Could not set max file descriptors to $MAX_FD" ;;
  esac
fi

exec "$JAVACMD" \
  $DEFAULT_JVM_OPTS \
  $JAVA_OPTS \
  $GRADLE_OPTS \
  "-Dorg.gradle.appname=$APP_BASE_NAME" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
